# Generated by Django 3.1.7 on 2021-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_number', models.IntegerField(default=0)),
                ('dealer_name', models.CharField(max_length=200)),
                ('dealer_address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_live_id', models.IntegerField()),
                ('vin', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=200, null=True)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('trim', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('miles', models.IntegerField()),
                ('exterior', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(default=0)),
                ('certified', models.BooleanField()),
                ('transmission', models.TextField(null=True)),
                ('body_type', models.CharField(max_length=200)),
                ('speeds', models.IntegerField(null=True)),
                ('doors', models.IntegerField(null=True)),
                ('cylinders', models.IntegerField(null=True)),
                ('engine', models.CharField(max_length=200, null=True)),
                ('displacement', models.IntegerField(null=True)),
                ('pincode', models.IntegerField(default=0)),
                ('phone', models.IntegerField(null=True)),
                ('dealer_number', models.IntegerField()),
                ('distance', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(default=0)),
                ('state_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
    ]
